version: '3'
services:
  web-service:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3100:80
    command: ["npm", "run", "debug"]
  mysql:
    image: mysql:8.0.35
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: gym
      MYSQL_USER: user_gym
      MYSQL_PASSWORD: 54321
volumes:
  mysql_data: